version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    ports:
      - "5433:5433"
    volumes:
      - ./data:/var/lib/postgresql/data



  app:
    build: .
    container_name: flask_test_2
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db