version: '3'
services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    ports:
      - "5433:5433"
    volumes:
      - ./data:/var/lib/postgresql/data



  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=postgresql://admin:admin@db/db