version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:admin@db/admin
    volumes:
      - ./uploads:/app/uploads
volumes:
  db_data: