version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  flask:
    build: .
    container_name: flask_test2
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
