version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "./uploads:/app/uploads"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/db:/var/lib/postgresql/data