version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5444:5444

  flask:
    build: .
    container_name: flask_test_2.1
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db