version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  flask:
    build: .
    container_name: flask_test2
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
